services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    networks:
      - tunnel-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  tunnel-net:
    driver: bridge

x-warp-routing:
  enabled: true
